name: Update Links and Deploy

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  push:
    branches:
      - main

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify package.json exists
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json is missing!"
            exit 1
          fi

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci  # This ensures a clean install based on package-lock.json

      - name: Verify Installed Modules
        run: npm list

      - name: Run script to fetch and update links
        run: node index-js/wizard-of-oz.js

      - name: Update Reward Page
        run: |
          echo '<div class="rewards">' > static/rewards/wizard-of-oz.md
          jq -r '.[] | "  <p><a href=\"" + .href + "\">" + .text + "</a></p>\n"' links-json/wizard-of-oz.json >> static/rewards/wizard-of-oz.md
          echo '</div>' >> static/rewards/wizard-of-oz.md

      - name: Configure Git
        run: |
          git config --global user.email "rohan735234@gmail.com"
          git config --global user.name "iamrohan99"

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add static/rewards/wizard-of-oz.md links-json/wizard-of-oz.json
          git commit -m "Update wizard-of-oz reward links" || true
          git pull --rebase
          
          for i in {1..5}; do
            git push && break
            echo "Retry $i: Push failed, retrying in 5 seconds..."
            sleep 5
            git pull --rebase
          done
