name: Update Links and Deploy

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  push:
    branches:
      - main

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install jq axios cheerio

      - name: Fetch and Update Links
        run: |
          node index-js/wizard-of-oz.js
          echo "Content of links-json/wizard-of-oz.json:"
          cat links-json/wizard-of-oz.json

      - name: Update Reward Page
        run: |
          echo '<div class="rewards">' > static/rewards/wizard-of-oz.md
          jq -r '.[] | "  <p><a href=\"" + .href + "\">" + .text + "</a></p>\n"' links-json/wizard-of-oz.json >> static/rewards/wizard-of-oz.md
          echo '</div>' >> static/rewards/wizard-of-oz.md
          echo "Content of static/rewards/wizard-of-oz.md:"
          cat static/rewards/wizard-of-oz.md

      - name: Configure Git
        run: |
          git config --global user.email "rohan735234@gmail.com"
          git config --global user.name "iamrohan99"

      - name: Commit and Push changes
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git add static/rewards/wizard-of-oz.md links-json/wizard-of-oz.json
          git commit -m "Update wizard-of-oz reward links" || true

          # Pull with rebase to ensure the latest changes are included
          git pull --rebase

          # Push changes, retry if necessary
          for i in {1..5}; do
            git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/iamrohan99/woz.git && break
            echo "Retry $i: Push failed, retrying in 5 seconds..."
            sleep 5
            git pull --rebase
          done
